### ISSUE TITLE
how to use runtime?

### ISSUE THREAD

**Issue by jeb2239** [nojb/llvm-tiger#1]
So based on the the code is seems like all you need to do is execute tigerc.native in the same directory as the runtime c files. when attempting to compile the "good" tests i get this error

``` sh
$ ../../tigerc.native arr0.tig
error: Invalid type for value
clang: error: no such file or directory: '/tmp/arr0457fd1.s'

```

the files in the directory are 

```
arr0.tig  arr-nil.tig     fact.tig  for-escapes.tig  lambdalift1.tig      nested0.tig  nil-cmp.tig  rec0.tig  rec3.tig       tiger_gc.c
arr1.tig  assign-nil.tig     gc0.tig          let-nil.tig          nested1.tig  print0.tig   rec1.tig  rec-nil.tig    tiger_stdlib.c
arr2.tig  break-phi.tig   for0.tig  lambdalift0.tig  mutually-recfns.tig  nested2.tig  queens.tig   rec2.tig  rec-types.tig

```

I was wondering if I am using this incorrectly.

**Comment by nojb** [comment]
Hi!  I haven't looked at the code for some time so I am not sure what is the cause.  I will take a look when I am back home today and get back to you.

Thanks!

**Comment by nojb** [comment]
Which version of llvm/clang do you have ?

**Comment by nojb** [comment]
I just tried the following

``` bash
cd llvm-tiger
make
cd runtime
../tigerc.main ../tests/good/queens.tig
./a.out
```

and it worked.  Some of the other tests may fail because the GC stuff is not really working at the moment, but the basic functionality works.  I will probably be working on this soon to get it into shape.

Let me know if it works for you!

**Comment by jeb2239** [comment]
I have been using 3.7 I will try what you just did. Thanks!

**Comment by jeb2239** [comment]
What branch are you on? Mine produces a .native file.

**Comment by nojb** [comment]
Sorry, typo.  `tigerc.main => tigerc.native`

**Comment by jeb2239** [comment]
```
../tigerc.native ../test/good/arr0.tig
error: Invalid type for value
>> Fatal error: command "llc /tmp/arr0ba27fd.bc" failed with code 1

```

this is what happens when i try that.
thanks for your help!

**Comment by nojb** [comment]
The compile works for me (it actually crashes at runtime due to some GC bug). I am using llvm 3.6, maybe there is a change in 3.7 that makes the `llc` invocation fail.

If you do

```
../tigerc.native -emit-llvm ../test/good/arr0.tig
```

you can take a look at `../test/good/arr0.ll` and try to see what is making `llc` fail.

**Comment by jeb2239** [comment]
```
../tigerc.native -S ../test/good/queens.tig
warning: overriding the module target triple with x86_64-pc-linux-gnu [-Woverride-module]
1 warning generated.
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../x86_64-linux-gnu/crt1.o: In function `_start':
/build/buildd/glibc-2.21/csu/../sysdeps/x86_64/start.S:114: undefined reference to `main'
/tmp/queens61d9fe-3dc0ee.o: In function `__tiger__main':
/tmp/queens61d9fe.bc:(.text+0xb0): undefined reference to `llvm_gc_allocate'
/tmp/queens61d9fe.bc:(.text+0xe6): undefined reference to `llvm_gc_allocate'
/tmp/queens61d9fe.bc:(.text+0x120): undefined reference to `llvm_gc_allocate'
/tmp/queens61d9fe.bc:(.text+0x15a): undefined reference to `llvm_gc_allocate'
/tmp/queens61d9fe-3dc0ee.o: In function `::printboard(void)':
/tmp/queens61d9fe.bc:(.text+0x253): undefined reference to `__tiger__print'
/tmp/queens61d9fe.bc:(.text+0x296): undefined reference to `__tiger__print'
/tmp/queens61d9fe.bc:(.text+0x2f4): undefined reference to `__tiger__print'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>> Fatal error: command "clang /tmp/queens61d9fe.bc -o ../test/good/queens.s" failed with code 1
```

and when emitting llvm i get 

```
 ../tigerc.native -emit-llvm ../test/good/queens.tig
llvm-dis: Invalid type for value
>> Fatal error: command "llvm-dis /tmp/queens408b6a.bc -o ../test/good/queens.ll" failed with code 1
```

I will work on this and let you know if I find a solution.

**Comment by jeb2239** [comment]
This works as expected. I had a version issue. This works with llvm and clang 3.6 and 3.7.
